package com.softeem.bean;

public class Clazz {
    @Override
    public String toString() {
        return "Clazz{" +
                "classId=" + classId +
                ", className='" + className + '\'' +
                ", grade=" + grade +
                ", departmentId=" + departmentId +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_name
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.grade
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.department_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_id
     *
     * @return the value of classes.class_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_id
     *
     * @param classId the value for classes.class_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_name
     *
     * @return the value of classes.class_name
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_name
     *
     * @param className the value for classes.class_name
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.grade
     *
     * @return the value of classes.grade
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.grade
     *
     * @param grade the value for classes.grade
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.department_id
     *
     * @return the value of classes.department_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.department_id
     *
     * @param departmentId the value for classes.department_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}