package com.softeem.bean;

import java.util.Date;


public class Student {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.student_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Integer studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.name
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.gender
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.birthdate
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.class_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.enrollment_date
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Date enrollmentDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.student_id
     *
     * @return the value of students.student_id
     *
     * @mbggenerated Tue Jan 23 16:44:02 CST 2024
     */
    private Clazz clazz;

    public Student() {
    }

    public Student(Integer studentId, String name, String gender, Date birthdate, Integer classId, Date enrollmentDate, Clazz clazz) {
        this.studentId = studentId;
        this.name = name;
        this.gender = gender;
        this.birthdate = birthdate;
        this.classId = classId;
        this.enrollmentDate = enrollmentDate;
        this.clazz = clazz;
    }

    /**
     * 获取
     * @return studentId
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * 设置
     * @param studentId
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * 获取
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * 设置
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取
     * @return gender
     */
    public String getGender() {
        return gender;
    }

    /**
     * 设置
     * @param gender
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * 获取
     * @return birthdate
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * 设置
     * @param birthdate
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * 获取
     * @return classId
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * 设置
     * @param classId
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * 获取
     * @return enrollmentDate
     */
    public Date getEnrollmentDate() {
        return enrollmentDate;
    }

    /**
     * 设置
     * @param enrollmentDate
     */
    public void setEnrollmentDate(Date enrollmentDate) {
        this.enrollmentDate = enrollmentDate;
    }

    /**
     * 获取
     * @return clazz
     */
    public Clazz getClazz() {
        return clazz;
    }

    /**
     * 设置
     * @param clazz
     */
    public void setClazz(Clazz clazz) {
        this.clazz = clazz;
    }

    public String toString() {
        return "Student{studentId = " + studentId + ", name = " + name + ", gender = " + gender + ", birthdate = " + birthdate + ", classId = " + classId + ", enrollmentDate = " + enrollmentDate + ", clazz = " + clazz + "}";
    }
}